spring.application.name=backend
            
# ===============================
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=RemotePatientMonitoringVer2;encrypt=true;trustServerCertificate=true;sendStringParametersAsUnicode=true;characterEncoding=UTF-8;

spring.datasource.username=sa
spring.datasource.password=sa


spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
# ===============================

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================

spring.jpa.hibernate.ddl-auto=update
server.port=8080
spring.thymeleaf.cache=false

# Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=lethang162005@gmail.com
spring.mail.password=wxks blgh asdz bhcn
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Response Encoding
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true

# OCR Python Configuration
ocr.python.command=python

# Multipart Upload Configuration
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
